name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:ci
      - run: bash <(curl -s https://codecov.io/bash)
